#Create Custom Container Image
#Push to DockerHub Registry
---
- hosts: localhost
  tasks: 
  - name: Pull .war artifact from Artifactory
    become: true
    get_url:
      url: http://13.212.136.2:8082/artifactory/libs-release/com/devops-proect/devops-project/1.0-RELEASE/devops-project-1.0-RELEASE.war
      dest: /home/admin
      url_username: admin
      url_password: <password>

  - name: Rename .war Artifact
    command: mv devops-project-RELEASE.war devops-project.war
  
  - name: Pull Tomcat  Container Image
    docker_image:
      name: tomcat:latest
      source: pull

  - name: Build image and with build args
    docker_image:
      name: devops-project
      build:
        path: /home/admin
        pull: no
        args:
          listen_port: 8080
      source: build

  - name: Log into DockerHub
    docker_login:
     username: <username>
     password: <password>
    
  - name: Push to docker hub
    docker_image:
      name: devops-project
      repository: devops-project/devops-project:1.0
      push: yes
      source: local
