#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-deploy
  labels:
    app: devops-project-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-project-app
  template:
    metadata:
      labels:
        app: devops-project-app
    spec:
      containers:
      - name: devops-project
        image: devops-project/devops-project:1.0
        ports:
        - containerPort: 8080
